version: '3.8'
services:
  php:
    build:
      args:
# same to id
        - UID=1000
        - GID=1000
        - USERNAME=oxtuser
        - XDEBUG_PORT=9003
        - PHP_SERVER_NAME=openexchangerates-oxt
#        - https_proxy=http://proxy.com:3128/
#        - http_proxy=http://proxy.com:3128/
