version: '3.8'
services:
  php:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/app:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  webserver:
    image: nginx:1.25.2-alpine
    depends_on:
      - php
    volumes:
      - ./:/app:ro
      - ./docker/webserver/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
