version: '3.8'
services:
  php:
    build:
      args:
        - UID=1001
        - GID=1001
        - XDEBUG_PORT=9003
        - PHP_SERVER_NAME=openexchangerates-oxt
#        - https_proxy=http://proxy.com:3128/
#        - http_proxy=http://proxy.com:3128/
